version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: test_node
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: user
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local